.\" Process this file with
.\" groff -man -Tutf8 roccatsuoracontrol.1
.\"
.TH ROCCATSUORACONTROL 1 "AUGUST 2016" "Stefan Achatz" "Benutzerhandbücher"
.SH NAME
roccatsuoracontrol \- Ein Hilfsprogramm um die erweiterten Funktionen der Roccat
Suora zu nutzen.
.SH SYNTAX
.B roccatsuoracontrol
[
.B -fhv
] [
.BI -a NAME
] [
.BI --activate-profile= NAME
] [
.B --game-mode-off
] [
.B --game-mode-on
] [
.B --help
] [
.B --read-firmware
] [
.B --reset
] [
.B --version
]
.SH BESCHREIBUNG
Diese Konsolenanwendung ermöglicht es die erweiterten Funktionen der Roccat
Suora zu nutzen.
.SH OPTIONEN
.IP "-h, --help"
Zeige die Hilfeliste.
.IP "-a, --activate-profile=NAME"
Lädt das angegebene Profil aus der Liste der verfügbaren Profile und speichert
es im Gerät.
.IP "--game-mode-off"
Deaktiviert den Spielmodus.
.IP "--game-mode-on"
Aktiviert den Spielmodus.
.IP "-f, --read-firmware"
Gibt die Firmwareversion der Suora aus.
.IP "--reset"
Setzt das Gerät auf Standardeinstellungen zurück.
.IP "-v, --version"
Zeige die Programmversion.
.SH AUTOR
Stefan Achatz <erazor_de@users.sourceforge.net>
